default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix", "--output-format=github"]
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [ "--fix", "--output-format=github" ]
