repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.7
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix", "--output-format=github"]
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: ["--fix", "--output-format=github"]
