name: G4F API

on: [push]

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m pytest tests/

      - name: Lint with Ruff
        run: ruff --output-format=github .
        continue-on-error: true

  deploy-coolify:
    name: Deploy app to https://g4f-api.cloud.mattf.one
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
      - run: curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
